name: Build and Upload Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # You can adjust to your preferred OS

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies (Qt and build tools)
    - name: Install Qt and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev build-essential

    # Step 3: Create build directory
    - name: Create build directory
      run: mkdir -p build

    # Step 4: Generate Makefile with qmake
    - name: Generate Makefile with qmake
      run: qmake project.pro -o build/Makefile  # Adjust path if necessary

    # Step 5: Build the project
    - name: Build the project
      run: make -C build

    # Step 6: Upload the built executable as artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: ./build/*.out  # Adjust this to match your actual executable
