name: Build, Upload, and Download Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install Qt and build tools
      - name: Install Qt and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev build-essential

      # Step 3: Create build directory
      - name: Create build directory
        run: mkdir -p build

      # Step 4: Generate Makefile with qmake
      - name: Generate Makefile with qmake
        run: qmake project.pro -o build/Makefile  # Adjust path if necessary

      # Step 5: Build the project
      - name: Build the project
        run: make -C build

      # Step 6: List files in the build directory to confirm the executable
      - name: List files in the build directory
        run: ls -la ./build

      # Step 7: Upload the built executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable  # This is the artifact name you need to reference in the next job
          path: ./build/atul  # Path to the executable file
          if-no-files-found: error

  download:
    needs: build  # Ensure this job waits for the `build` job to complete
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Download the uploaded artifact
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: executable  # Ensure this matches the name used in the upload step
          path: ./release    # Directory where the artifact will be downloaded

      # Step 3: List files in the release directory to verify download
      - name: List Files
        run: ls -R ./release
